# Change these first
owner: MerchantsBonding # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: MBC
    url: https://secure2.merchantsbonding.com/up
  - name: Hubble
    url: https://hub.merchantsbonding.com/up
  - name: MBC (Staging)
    url: https://secure2.mbctestweb.com/up
  - name: Hubble (Staging)
    url: https://hub.mbctestweb.com/up

status-website:
  publish: true
  baseUrl: /upptime
  url: https://fantastic-happiness-2e9o2ow.pages.github.io
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Merchants Bonding Status
  introTitle: "Merchants Status Page"
  introMessage: Uptime status of Merchants' apps.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
